# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea661e42827822b1a23daca2fadcfe49442f6c54dd567c99ea7c1e3abc6f6c88f9213347e94df5e15b3d92fd272abbd680c1a42c1fb5cc0c2a35597cd74c879

test:
  secret_key_base: 7fd5ae159e15a2f4a0f101cb13afd44bed3e4a585abe2499ed50195054fa75f88b79c6c75c4192af372793ad56337d9848bedb9c1923ffcb6ff4ff706a3f1b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
